- name: github-commit-to-trello-card
  uses: dalezak/github-commit-to-trello-card@v3

name: GitHub Commit To Trello Comment

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: dalezak/github-commit-to-trello-card@main
        with:
          trello-api-key: ${{ secrets.6c77c68ae53b2fce4028ea092517c1a3 }}
          trello-auth-token: ${{ secrets.dc526e466aabad8d3d6d0317ead9641ebc7aa7df14c592bdc8f9baa84481180c }}
          trello-board-id: ${{ secrets.https://trello.com/b/5yvM33Mc/testi.json }}
          trello-card-action: "Attachment"
          trello-list-name-commit: "Doing"
          trello-list-name-pr-open: "Reviewing"
          trello-list-name-pr-closed: "Testing"
