name: GitHub Commit To Trello Comment

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: dalezak/github-commit-to-trello-card@main
        with:
          trello-api-key: 6c77c68ae53b2fce4028ea092517c1a3
          trello-auth-token: dc526e466aabad8d3d6d0317ead9641ebc7aa7df14c592bdc8f9baa84481180c
          trello-board-id: https://trello.com/b/5yvM33Mc/testi
          trello-card-action: "Comment"
          trello-list-name-commit: "Doing"
          trello-list-name-pr-open: "Reviewing"
          trello-list-name-pr-closed: "Testing"
